services:
  java:
    image: sgx-demo:latest
    build: .
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
      - "/dev/sgx/enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"